import type { AnalyticsPoint, AuditLog, Checkin, Escalation, Goal, Notification, User } from "../types";

export const users: User[] = [
  {
    id: "u-employee",
    name: "Maya Raman",
    email: "employee@alignx.com",
    role: "employee",
    title: "Product Marketing Specialist",
    department: "Growth",
    managerId: "u-manager",
    avatar: "MR",
  },
  {
    id: "u-manager",
    name: "Arjun Mehta",
    email: "manager@alignx.com",
    role: "manager",
    title: "Director, Growth",
    department: "Growth",
    avatar: "AM",
  },
  {
    id: "u-admin",
    name: "Neha Kapoor",
    email: "admin@alignx.com",
    role: "admin",
    title: "People Operations Lead",
    department: "People",
    avatar: "NK",
  },
  {
    id: "u-2",
    name: "Riya Sen",
    email: "riya@alignx.com",
    role: "employee",
    title: "Customer Success Manager",
    department: "Customer Success",
    managerId: "u-manager",
    avatar: "RS",
  },
  {
    id: "u-3",
    name: "Kabir Sethi",
    email: "kabir@alignx.com",
    role: "employee",
    title: "Revenue Analyst",
    department: "Finance",
    managerId: "u-manager",
    avatar: "KS",
  },
];

export const goals: Goal[] = [
  {
    id: "g-1",
    ownerId: "u-employee",
    title: "Launch enterprise adoption playbook",
    description: "Create and roll out a repeatable enterprise onboarding playbook for top accounts.",
    metric: "Playbook adopted by 8 strategic accounts",
    weight: 30,
    progress: 72,
    status: "approved",
    dueDate: "2026-06-28",
    managerComment: "Strong scope. Keep enablement notes crisp for regional teams.",
    updatedAt: "2026-05-16 10:24",
  },
  {
    id: "g-2",
    ownerId: "u-employee",
    title: "Improve qualified pipeline conversion",
    description: "Partner with sales to tighten campaign targeting and improve SQL handoff quality.",
    metric: "Increase MQL to SQL conversion from 22% to 29%",
    weight: 35,
    progress: 58,
    status: "approved",
    dueDate: "2026-06-30",
    updatedAt: "2026-05-14 15:02",
  },
  {
    id: "g-3",
    ownerId: "u-employee",
    title: "Build quarterly customer proof library",
    description: "Publish outcome stories and quantified proof points for revenue teams.",
    metric: "12 proof assets published and tagged",
    weight: 25,
    progress: 46,
    status: "submitted",
    dueDate: "2026-06-20",
    updatedAt: "2026-05-17 09:13",
  },
  {
    id: "g-4",
    ownerId: "u-employee",
    title: "Run competitive messaging refresh",
    description: "Refresh competitive battlecards for the highest-volume win/loss segments.",
    metric: "4 battlecards validated by sales leadership",
    weight: 10,
    progress: 20,
    status: "draft",
    dueDate: "2026-06-15",
    updatedAt: "2026-05-12 12:05",
  },
  {
    id: "g-5",
    ownerId: "u-2",
    title: "Reduce onboarding time for mid-market accounts",
    description: "Standardize kickoff assets and customer health checkpoints.",
    metric: "Median onboarding time below 18 days",
    weight: 40,
    progress: 81,
    status: "submitted",
    dueDate: "2026-06-26",
    updatedAt: "2026-05-15 11:40",
  },
  {
    id: "g-6",
    ownerId: "u-3",
    title: "Create weekly revenue forecast model",
    description: "Automate forecast inputs and variance reporting for leadership.",
    metric: "Forecast variance under 6%",
    weight: 45,
    progress: 64,
    status: "submitted",
    dueDate: "2026-06-22",
    updatedAt: "2026-05-13 17:22",
  },
];

export const checkins: Checkin[] = [
  {
    id: "c-1",
    goalId: "g-1",
    quarter: "Q2",
    achievement: "Completed playbook draft and piloted it with three enterprise accounts.",
    confidence: 82,
    status: "reviewed",
    managerComment: "Good momentum. Add clearer owner handoffs for post-sale teams.",
    updatedAt: "2026-05-15 09:30",
  },
  {
    id: "c-2",
    goalId: "g-2",
    quarter: "Q2",
    achievement: "Campaign criteria updated. First two cohorts show improved opportunity quality.",
    confidence: 70,
    status: "submitted",
    updatedAt: "2026-05-16 16:18",
  },
  {
    id: "c-3",
    goalId: "g-5",
    quarter: "Q2",
    achievement: "New kickoff template reduced back-and-forth in pilot accounts.",
    confidence: 76,
    status: "submitted",
    updatedAt: "2026-05-12 13:44",
  },
];

export const notifications: Notification[] = [
  {
    id: "n-1",
    userId: "u-employee",
    title: "Goal awaiting approval",
    body: "Your proof library goal is with Arjun for review.",
    type: "approval",
    unread: true,
    createdAt: "2026-05-17 09:15",
  },
  {
    id: "n-2",
    userId: "u-manager",
    title: "Two approvals need review",
    body: "Riya and Kabir have submitted Q2 goals for approval.",
    type: "approval",
    unread: true,
    createdAt: "2026-05-16 18:10",
  },
  {
    id: "n-3",
    userId: "u-admin",
    title: "Escalation threshold reached",
    body: "Three items have been open for more than five business days.",
    type: "reminder",
    unread: true,
    createdAt: "2026-05-18 08:30",
  },
  {
    id: "n-4",
    userId: "u-employee",
    title: "Q2 check-in reminder",
    body: "Update achievements before Friday to keep your review packet current.",
    type: "reminder",
    unread: false,
    createdAt: "2026-05-14 10:00",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "a-1",
    actorId: "u-manager",
    action: "Approved goal",
    target: "Launch enterprise adoption playbook",
    detail: "Goal locked for Q2 tracking.",
    createdAt: "2026-05-16 10:24",
  },
  {
    id: "a-2",
    actorId: "u-employee",
    action: "Submitted goal",
    target: "Build quarterly customer proof library",
    detail: "Weightage set to 25%.",
    createdAt: "2026-05-17 09:13",
  },
  {
    id: "a-3",
    actorId: "u-admin",
    action: "Opened cycle",
    target: "Q2 2026",
    detail: "Cycle configured for goal approvals and check-ins.",
    createdAt: "2026-05-01 08:00",
  },
  {
    id: "a-4",
    actorId: "u-manager",
    action: "Reviewed check-in",
    target: "Enterprise adoption playbook",
    detail: "Manager comment added.",
    createdAt: "2026-05-15 09:30",
  },
];

export const escalations: Escalation[] = [
  {
    id: "e-1",
    ownerId: "u-2",
    managerId: "u-manager",
    reason: "overdue_approval",
    severity: "high",
    daysOpen: 7,
    status: "open",
  },
  {
    id: "e-2",
    ownerId: "u-3",
    managerId: "u-manager",
    reason: "overdue_checkin",
    severity: "medium",
    daysOpen: 5,
    status: "monitoring",
  },
  {
    id: "e-3",
    ownerId: "u-employee",
    managerId: "u-manager",
    reason: "overdue_approval",
    severity: "low",
    daysOpen: 3,
    status: "monitoring",
  },
];

export const completionTrend: AnalyticsPoint[] = [
  { label: "Jan", value: 54 },
  { label: "Feb", value: 61 },
  { label: "Mar", value: 68 },
  { label: "Apr", value: 72 },
  { label: "May", value: 79 },
  { label: "Jun", value: 84 },
];

export const departmentPerformance: AnalyticsPoint[] = [
  { label: "Growth", value: 82 },
  { label: "Sales", value: 76 },
  { label: "Product", value: 88 },
  { label: "CS", value: 73 },
  { label: "Finance", value: 69 },
];

export const managerPerformance: AnalyticsPoint[] = [
  { label: "Arjun", value: 91, secondary: 4 },
  { label: "Priya", value: 84, secondary: 6 },
  { label: "Dev", value: 78, secondary: 8 },
  { label: "Sara", value: 87, secondary: 3 },
];
